export {default as Home} from './Home/Home';
export {default as Login} from './Login/Login';
export {default as LandingPage} from './LandingPage/LandingPage';
export {default as StudentProfile} from './StudentProfile/StudentProfile';
export {default as StudentsCourse} from './StudentsCourse/StudentsCourse';
export {default as StudentDashboard} from './StudentDashboard/StudentDashboard';
export {default as AvailableCourses} from './AvailableCourses/AvailableCourses';
export {default as EnrollCourse} from './StudentsCourse/EnrollCourse/EnrollCourse';
export {default as CourseDetails} from './StudentsCourse/CourseDetails/CourseDetails';
