export {default as Facebook} from './Svgs/Facebook';
export {default as Instagram} from './Svgs/Instagram';

type images = {
  [key: string]: string;
};

export const IMAGES: images = {
  Oil: require('./Images/oil.jpeg'),
  Kid2: require('./Images/kid2.jpg'),
  Kid3: require('./Images/kid3.jpg'),
  Kid4: require('./Images/kid4.jpg'),
  Kid5: require('./Images/kid5.jpg'),
  oil1: require('./Images/oil1.jpeg'),
  oil2: require('./Images/oil2.jpeg'),
  oil3: require('./Images/oil3.jpeg'),
  oil4: require('./Images/oil4.jpeg'),
  Kid1: require('./Images/kids1.jpeg'),
  Resin: require('./Images/resin.jpeg'),
  KidsArt: require('./Images/kids.jpeg'),
  resin1: require('./Images/resin1.jpeg'),
  resin2: require('./Images/resin2.jpeg'),
  resin3: require('./Images/resin3.jpeg'),
  resin4: require('./Images/resin4.jpeg'),
  Mosaic: require('./Images/Mosaic.jpeg'),
  Logo: require('./Images/AfnanLogo.jpg'),
  Acrylic: require('./Images/acrylic.jpg'),
  warning: require('./Images/warning.png'),
  Macrame: require('./Images/macrame.jpeg'),
  mosaic1: require('./Images/mosaic1.jpeg'),
  mosaic2: require('./Images/mosaic2.jpeg'),
  mosaic3: require('./Images/mosaic3.jpeg'),
  acrylic1: require('./Images/acrylic1.jpeg'),
  acrylic2: require('./Images/acrylic2.jpeg'),
  acrylic3: require('./Images/acrylic3.jpeg'),
  Sketching: require('./Images/sketching.jpeg'),
  sketching1: require('./Images/sketching1.jpeg'),
  sketching2: require('./Images/sketching2.jpeg'),
  sketching3: require('./Images/sketching3.jpeg'),
  sketching4: require('./Images/sketching4.jpeg'),
  instructors1: require('./Images/Instructors1.png'),
  instructors2: require('./Images/Instructors2.png'),
  instructors3: require('./Images/Instructors3.png'),
  instructors4: require('./Images/Instructors4.png'),
  carousel1: require('./Images/carousel1.jpeg'),
  carousel2: require('./Images/carousel2.jpeg'),
  carousel3: require('./Images/carousel3.jpeg'),
  carousel4: require('./Images/carousel4.jpeg'),
  carousel5: require('./Images/carousel5.jpeg'),
  carousel6: require('./Images/carousel6.jpeg'),
  carousel7: require('./Images/carousel7.jpeg'),
  carousel8: require('./Images/carousel8.jpeg'),
  carousel9: require('./Images/carousel9.jpeg'),
  carousel10: require('./Images/carousel10.jpeg'),
  carousel11: require('./Images/carousel11.jpeg'),
  carousel12: require('./Images/carousel12.jpeg'),
  carousel13: require('./Images/carousel13.jpeg'),
  carousel15: require('./Images/carousel15.jpeg'),
  carousel16: require('./Images/carousel16.jpeg'),
};

export const ANIMATION = {
  login1: require('./Animation/animation_1.json'),
  login2: require('./Animation/animation_2.json'),
  login3: require('./Animation/an_4.json'),
  login4: require('./Animation/art.json'),
};
